### ISSUE TITLE
No Constructor for FlywayConfiguration class

### ISSUE THREAD

**Issue by b-twis** [bunomonteiro/flyway.net#1]
Hello Bruno

Readme shows that there should eb a construtor taking FlywayConfiguration object, but this seems to be missing in code. There is only the ability to load configuration from a file. 

```c#
// with config in memory
var config = new FlywayConfiguration();
config.Url.Value = "jdbc:...";
await new Flyway(config).MigrateAsync();
```

Is is possible for you to fix this and publish a new version to nuget?

Thanks,
Basil

**Comment by bunomonteiro** [comment]
😲

Dude, I'm sorry for the delay! 
I'm so pressed for time, that I could only read your comment right now.

Well, this is so strange cuz I remember it was possible.
I'll fix it and publish now.

**Comment by bunomonteiro** [comment]
It's done! 😁

Thanks man, for your report!
